package main 

import (
    "fmt"
    "testing"
)

func testcredential (t *testing.T) {
    main()
    panic(fmt.Errorf("there is an error"))        
}
